import Components from "./ReactNativeElements";

const Styles = Components.StyleSheet.create({
    ScrollContainer: {
        flexGrow: 1,
        backgroundColor: "#d11589ff",
        paddingHorizontal: 15,
        paddingVertical: 10,
        rowGap: 10,
    },

    SafeAreaContainer: {
        flex: 1,
        backgroundColor: "#ffffff",
    },

    KeyboardAvoidingContainer: {
        flex: 1,
        justifyContent: "center",
        backgroundColor: "#f8f9fb",
    },

    LoginContainer: {
        flex: 1,
        padding: 20,
        backgroundColor: "#094dbaff",
        borderRadius: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 5,
        rowGap: 10,
        height: "auto",
        maxWidth: "95%",
        marginLeft: "2.5%",
        justifyContent: "center",
        
    },    
    Container: {
        flex: 1,
        padding: 20,
        backgroundColor: "transparent",
        rowGap: 10,
        maxHeight: "50%",
        borderRadius: 15,
        shadowColor: "#dfd5d5ff",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 4,
    },

    InputFileds: {
        backgroundColor: "#ffffff",
        borderRadius: 10,
        borderWidth: 1,
        borderColor: "#dce1eb",
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16,
        color: "#333",
        marginBottom: 15,
    },

    Lables: {
        fontSize: 40,
        fontWeight: "600",
        color: "#061051ff",
        marginBottom: 6,
        alignSelf: "center",
    },

    Navigaters: {
        flexDirection: "row",
        justifyContent: "space-between",
        justifyContent: "center",
        backgroundColor: "#6c63ff",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
    },

    Stacks: {
        flexDirection: "column",
        gap: 10,
    },

    Images: {
        width: "100%",
        height: 200,
        resizeMode: "cover",
        borderRadius: 12,
        marginBottom: 15,
    },

    Button: {
        backgroundColor: "#6c63ff",
        paddingVertical: 15,
        borderRadius: 10,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
    },

    ButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },

    List: {
        backgroundColor: "#fff",
        padding: 15,
        marginVertical: 8,
        borderRadius: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },

    Indicators: {
        alignSelf: "center",
        marginVertical: 20,
    },
        toDoSafeArea: {
        flex: 1,
        backgroundColor: '#181c2f',
    },
    toDoKeyboardAvoiding: {
        flex: 1,
        justifyContent: 'flex-start',
        backgroundColor: 'transparent',
    },
    toDoContainer: {
        flex: 1,
        backgroundColor: '#23284d',
        marginTop: 0,
        borderRadius: 0,
        minHeight: '100%',
        padding: 20,
    },
    toDoTitle: {
        color: '#f7c948',
        fontSize: 32,
        marginTop: 24,
        marginBottom: 18,
        fontWeight: 'bold',
        letterSpacing: 1,
        alignSelf: 'flex-start',
    },
    toDoInputRow: {
        flexDirection: 'row',
        marginBottom: 18,
    },
    toDoInput: {
        flex: 1,
        backgroundColor: '#23284d',
        color: '#f7c948',
        borderColor: '#f7c948',
        borderWidth: 1,
        borderRadius: 10,
        fontWeight: '600',
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16,
    },
    toDoAddButton: {
        marginLeft: 8,
        backgroundColor: '#f7c948',
        borderRadius: 10,
        paddingVertical: 15,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 18,
    },
    toDoAddButtonText: {
        color: '#23284d',
        fontWeight: 'bold',
        fontSize: 16,
    },
    toDoScroll: {
        backgroundColor: 'transparent',
    },
    toDoEmptyText: {
        textAlign: 'center',
        color: '#b2b7d1',
        fontSize: 16,
        marginTop: 32,
    },
    toDoListItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#23284d',
        borderColor: '#f7c948',
        borderWidth: 1,
        marginVertical: 8,
        paddingVertical: 12,
        paddingHorizontal: 10,
        borderRadius: 12,
    },
    toDoTaskText: {
        fontSize: 18,
        color: '#f7c948',
        fontWeight: '600',
        letterSpacing: 0.5,
    },
    toDoTaskTextCompleted: {
        color: '#b2b7d1',
        textDecorationLine: 'line-through',
    },
    toDoToggleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 10,
    },
    toDoToggle: {
        width: 80,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#e74c3c',
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#f7c948',
        position: 'relative',
        marginHorizontal: 6,
        padding: 0,
    },
    toDoToggleDone: {
        backgroundColor: '#2ecc71',
    },
    toDoToggleKnob: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#181c2f',
        position: 'absolute',
        top: 4,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#f7c948',
    },
    toDoToggleLabel: {
        color: '#fff',
        fontSize: 13,
        fontWeight: 'bold',
        letterSpacing: 0.5,
        marginHorizontal: 6,
    },
    toDoDeleteButton: {
        marginLeft: 8,
    },
    toDoDeleteButtonText: {
        color: '#e74c3c',
        fontWeight: 'bold',
        fontSize: 15,
    },
});

export default Styles;
